### ISSUE TITLE
PICO-PI-IMX7 - Device is Locked

### ISSUE THREAD

**Issue by toni1727** [technexion-android/cookers#12]
Hello, I write because I am quite desperate with your products.

I have a PICO-PI-IMX7 board and donwload and compile your repo:

source cookers/env.bash.imx7d.pico-imx7.pi.lcd-5-inch

I try to flash the image with:

uuu_imx_android_flash.bat -f imx7d

but I always get the same error:

Error: fail open file: >u-boot-imx7d-sabresd-uuu.imx.link

How can I generate that file?

Best regards.

**Comment by wigcheng** [comment]
Hi!
I suggest do not use fastboot script to flash images, it need unlock first using so much steps.
You can use our flashcard steps from instruction of cookers, do you use it before?

Quick way is mount eMMC as mass storage via u-boot ums command, and issue commands from host PC as following:

$ flashcard /dev/sdx 3

It should be works.

**Comment by toni1727** [comment]
Boot console:

FSL_SDHC: 0 (eMMC)
FSL_SDHC: 1
=>   ums 0 mmc 0
UMS: LUN 0, dev 0, hwpart 0, sector 0x0, count 0x720000
- \ / -

BUT IT DOES NOT CREATE MASS STORAGE

and if I call:

flashcard /dev/sdx 3

/dev/sdx:
 re-reading partition table
 BLKRRPART failed: Inappropriate ioctl for device

Could you tell me how generate  u-boot-imx7d-sabresd-uuu.imx.link file?

Best regards.

EDIT:

I resolverd generating full image with:

"gen_virtual_images"

But Android 9 works really badly with imx7d. Maybe little power or little ram.

Thank you!

**Comment by wigcheng** [comment]
RAM need 1GB at least.
