### ISSUE TITLE
Building for wandboard_qca, image won't boot

### ISSUE THREAD

**Issue by thomasLavocat** [technexion-android/cookers#19]
Hi,

Yesterday i followed https://github.com/technexion-android/cookers/tree/tn-o8.0.0_1.0.0-ga to compile an android 8 image for the wandboard with pixi9377 chip.

I dit those manipulations :

```
repo init -u https://github.com/technexion-android/manifest -b tn-o8.0.0_1.0.0-ga
repo sync -j8
cd cookers
docker build -t build_droid8 .
sudo docker run --privileged=true --name mx8_build  -v /home/tlavocat/technexion:/home/mnt -t -i build_droid8 bash
cd /home/mnt
source cookers/env.bash.imx6.edm1cf-pmic.wandboard.hdmi

# unzip wifi firmware in device/fsl/wandboard/wifi-firmware/

merge_restricted_extras
cook -j8
cd ~technexion/out/target/product/wandboard/
flashcard /dev/sdb
```

Upon boot, I can see on the screen the wandboard logo displaying for less than 1 second and then only a blackscreen.

What can I do to make it work ?
Thanks for your answers,
Thomas

**Comment by wigcheng** [comment]
Could you provide console log if possible? I need to check your system stocking on u-boot or kernel, thanks.

**Comment by thomasLavocat** [comment]
I have the logs you asked. I'm giving you two logs with two distinct errors.

[minicom-d1-qca-bug1.log](https://github.com/technexion-android/cookers/files/4896838/minicom-d1-qca-bug1.log)
[minicom-d1-qca-bug2.log](https://github.com/technexion-android/cookers/files/4896840/minicom-d1-qca-bug2.log)

Somehow there is a second issue at stake here. I've also experienced it with our custom android 7 image. I will open an third issue on the subject if you don't mind.
