### ISSUE TITLE
TechNexion Android tn-p9.0.0_2.0.1_8m-ga_tn1.0 default mode in landscape

### ISSUE THREAD

**Issue by veerpawan** [technexion-android/cookers#26]
Hi, I tried to flash the Android tn-p9.0.0_2.0.1_8m-ga_tn1.0 image on the TechNexion board but the default orientation is Landscape. Please let me know how I can make it Portraint?

**Comment by wigcheng** [comment]
Did you try this ???
https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.0.1_8m-ga#change-the-display-rotation-angle-when-boot

**Comment by veerpawan** [comment]
Already Tried that. changed the file, build and then flash on the board. but still, the orientation is landscape.

**Comment by wigcheng** [comment]
Try getprop | grep "hwrotation" commit and feedback ouput here.

**Comment by veerpawan** [comment]
Here is the modified code


KERNEL_NAME := Image
BOARD_KERNEL_CMDLINE := init=/init androidboot.hwrotation=90 androidboot.console=ttymxc1 androidboot.hardware=freescale cma=$(CMASIZE) androidboot.primary_display=imx-drm firmware_class.path=/vendor/firmware transparent_hugepage=never

**Comment by wigcheng** [comment]
No, I mean issue command to check current mode at runtime stage as follows
# getprop | grep "hwrotation"

thanks

**Comment by veerpawan** [comment]
Thanks for the reply wigcheng..

Done this module by changing the launcher mode to portrait and now the complete Android 9 Image in Portrait.

**Comment by veerpawan** [comment]
Please hava a look on this 
**Do you change source code so much especially init.rc?**
Didn't touch init.rc

**You forgot provide dmesg log to me (just type dmesg in console and save as txt file to me), please provide it.**

demsg.txt

**Make sure your firmware path is correct, provide me the output log when issue "ls /vendor/etc/firmware/"**

bdwlan30.bin imx otp30.bin qca qwlan30.bin tfa98xx.cnt utf30.bin wlan
[demsg (1).txt](https://github.com/technexion-android/cookers/files/5879779/demsg.1.txt)

**Comment by wigcheng** [comment]
It seems you already fix landscape issue, please close this ticket first.
Separate topics is more clean to read, so don't post wifi relate discussion here, thanks a lot!
