### ISSUE TITLE
10.1" Display Touch screen Problem

### ISSUE THREAD

**Issue by ChatchaiBuekban** [technexion-android/cookers#30]
Hi.

I found some bug on the touch screen and now I fixed it with edit imx8mm-pico-wizard-g101uan02.dts file and now works perfectly.

This fix correct?

&i2c3 {
        /*polytouch: edt-ft5826@38*/                        //  *********** Old **/
	polytouch: edt-ft5x06@38 {                           //  fixed    
		compatible = "edt,edt-ft5x06";
		reg = <0x38>;
		pinctrl-names = "default";
		pinctrl-0 = <&pinctrl_touch_irq>;
		interrupt-parent = <&gpio1>;
		interrupts = <7 IRQ_TYPE_EDGE_FALLING>;
		reset-gpios = <&pca9555_23 3 GPIO_ACTIVE_LOW>;
		touchscreen-size-x = <1920>;
		touchscreen-size-y = <1200>;
		ten_inch_tp;     //test                      // just try      
		status = "okay"; //test                    // just try
	};
};

Thanks.

**Comment by ChatchaiBuekban** [comment]
and can't touch when display in lock screen mode

**Comment by wigcheng** [comment]
My touch works fine here including screen unlock as follows video link:
https://www.youtube.com/watch?v=tDRbzziSKtk&feature=youtu.be

In addition, I think touchscreen node of dts no need to do modification because that just name definition, should be works fine if driver loading is correct.

**Comment by ChatchaiBuekban** [comment]
Ok, I will back to old dts and try again.

**Comment by ChatchaiBuekban** [comment]
Please check my video here, 

https://drive.google.com/file/d/1dVyCAuzQ-nb5XTf5ghT-aU6HC_Kq2cO5/view?usp=sharing

I can't touch it when I use the original dts file :(

**Comment by wigcheng** [comment]
Because you modify the rotation angle to 90 degree using KERNEL_CMDLINE, right? 
Default setting of touchscreen is for landscape mode, you need modify dts if you want to do rotation.

I recommend you recover KERNEL_CMDLINE first and try again.

**Comment by ChatchaiBuekban** [comment]
Yes, I rotate screen to 90 degree. but not using KERNAL_CMDLINE , I just change default hardware rotation 0 to 90  in BroadConfig.mk file. 

Please recommend me if I need  change rotation by default.

Thanks.

**Comment by wigcheng** [comment]
Just tested rotation to 90 in BroadConfig.mk file, it still works perfectly, I have no other modification.
Could you check your modification first? I recommend back up your all modification, then recover your source code and clean build again.

And keep commit your modification if it works.
