### ISSUE TITLE
Application as system app

### ISSUE THREAD

**Issue by VaporMontey** [technexion-android/cookers#32]
Hello,

I would like to add my application as a system app, how can I do it?

Also, it's possible to create an image with root access?

**Comment by wigcheng** [comment]
What kind of your app, prebuilt apk or it's source code which made by android studio?

You can refer our repos as follows:
1. prebuilt apk
https://github.com/technexion-android/platform_packages_apps_EDM_CANBUS_PRE
2. source code
https://github.com/technexion-android/packages_apps_GpiodJniTest

then add apk name to makefile in device/nxp folder, it should be works


In addition, I don't understand what's root access? You mean the rootfs has write permission, or default is root user ( no need issue 'su' command to login as root user).

Thanks

**Comment by VaporMontey** [comment]
Hello @wigcheng,

Thanks for the reply, with root access I mean making an image where default is root user.

Best regards

**Comment by wigcheng** [comment]
You can try engineer mode as follows page:
https://source.android.com/setup/develop/new-device#build-variants

Add eng mode to <source>/device/nxp/imx8m/AndroidProducts.mk, for example:
pico_imx8mm-eng

But it's zero security, I don't think root user as defualt configuration is a good idea :)

Thanks

**Comment by VaporMontey** [comment]
Thanks a lot for the info, one last thing, how do I reboot in fastboot mode? I did this command without success:

$ adb root

Then in "Developer Options" -> I've checked "OEM unlocking" and I've rebooted the device.
When I issue the command "$ adb reboot bootloader" the device just restart and won't enter fastboot mode

Best regards

**Comment by VaporMontey** [comment]
Hello,

I dont have /device/nxp folder in Android 9 source code, Should I create it?
Where is makefile? Where do I add the apk?

Should I just add the app source to /packages/apps ?

Best regards

**Comment by wigcheng** [comment]
I thought you're using Android 11, Android 9 path is /device/fsl/imx8m/AndroidProducts.mk.

which board do you use, PICO-IMX8MM or PICO-IMX8M?

**Comment by VaporMontey** [comment]
I'm using TEP 0700 (IMX7D) board, should I use /device/fsl/imx7d/AndroidProducts.mk?

**Comment by wigcheng** [comment]
YES, please try it first

**Comment by VaporMontey** [comment]
Hello,

Sorry for my noob questions but it's my first time making this images.

Finally I've managed to make the image but I have an issue fashing it:
I've seen the documentation on GitHub it's for mainly PICO boards because it requires the use of imx-mfg-uuu-tool to flash the image. I'm using TEP board that doesn't have serial mode but I can only mount its eMMC as an internal storage, how can I create an installer image or a prebuilt image-like to flash it directly to the eMMC using Win32 disk imager?

Best regards

**Comment by wigcheng** [comment]
Never mind! TEP1-IMX7 no need UUU tools. 
You have to mount your eMMC as a mass storage first, then issue flash command as follows instruction:

https://developer.technexion.com/docs/android-pie-arm32-setup-build-and-flashing#flashing-the-output-images


Thanks

**Comment by wigcheng** [comment]
Or use this installer, flash to the SD card first, and it will auto mount eMMC as mass storage:

https://download.technexion.com/demo_software/TEP/IMX7/tep0500-imx7d/Installer/tep1-imx7d_generic_installer_TTL_LCD-800x480_20210727.zip

**Comment by VaporMontey** [comment]
Thank you, I've managed to flash it and it's working.

Best regards
