### ISSUE TITLE
TEP 0700 imx7 RS232 not working properly

### ISSUE THREAD

**Issue by VaporMontey** [technexion-android/cookers#33]
Hello,

I'm trying to use the RS232 port on the TEP (model TEP0700IMX7DR10E04L130) but I'm having lot's of issues.

Using Android 9 2.2.0 from [your repository](https://download.technexion.com/images/tep1-imx7/tep1-070/android-9.0.xz) and settings selinux to permissive (`setenforce 0`) will give me some reading issue.
I'm using the port /dev/ttymxc2 with my application based on your [uart test](https://github.com/technexion-android/platform_packages_apps_UartTestAarch64/tree/tn-p9.0.0_2.2.0-ga) but I can only write to the port and cannot read properly. Most of the time when reading it won't return nothing, sometimes it gives me the expected data.

Using the same application with the same configuration but on Android 7.1.1 from your [repository](https://download.technexion.com/demo_software/TEP/IMX7/tep0700-imx7d/archived/tep1-imx7d_android-7.1.1_installer_lcd-800x480_20180717.zip) gives me a fully working RS232 port.

Is there something to configure on Android 9 to make the RS232 port properly working?

Best regards

**Comment by VaporMontey** [comment]
Using your UART test app and testing loopback shows this values in Loopback activity:

17 received
1443 corrupted

**Comment by wigcheng** [comment]
Could you provide your order date or serial number, I would like to lookup your hardware revision first.

**Comment by VaporMontey** [comment]
Hello,

This is the serial number: 00000277ad394862

Best regards

**Comment by wigcheng** [comment]
> 00000277ad394862

Is it a order number or a serial number on the TEP-IMX7 case?

**Comment by VaporMontey** [comment]
Sorry, it was the number provided by Android, on the back of the TEP I have these:

Part No: S600406010040360000511
Serial No: 17202213300018270014
Model Name: TEP0700IMX7DR10E04L130

**Comment by wigcheng** [comment]
Oops, your TEP-IMX7 is another revision (A1), Android 9 does support revision A2 only:
https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.2.0-ga#starting-compile-the-source-code

There are different hardware configuration, but it's okay, I can provide you patch but you have to compile image by yourself, is it okay?



Thanks

**Comment by VaporMontey** [comment]
Yes, no problem.

There is a way to spot a TEP A1 vs A2?

Best regards

**Comment by wigcheng** [comment]
No, that is support list, let you know Android 9 does support A2 only, I’ll send you A1 patches to you tomorrow (Taipei time), thanks a lot

**Comment by wigcheng** [comment]
Here is the patches as follows link:

1. device tree
https://www.dropbox.com/s/mh6nn74zzqalz0g/imx7d-tep1.dtsi?dl=0
Please copy to (source code)/vendor/nxp-opensource/kernel_imx/arch/arm/boot/dts/imx7d-tep1.dtsi 
2. BoardConfig.mk
https://www.dropbox.com/s/kx022iexl9epztq/BoardConfig.mk?dl=0
change default dtb file using a1 revision device tree, please copy to (source code)/device/fsl/imx7d/tep1_imx7/BoardConfig.mk
3. init.rc
https://www.dropbox.com/s/e0lf7c3p0vaut9n/a1-change.patch?dl=0
Setting permission for UARTs of a1 revision, please copy to (source code)/device/fsl/ and use 'git apply' command

Thanks

**Comment by VaporMontey** [comment]
Hello,

Thanks for the patch, I'll let you know how it goes.

Best regards

**Comment by VaporMontey** [comment]
@wigcheng The patch works perfectly, thanks a lot for your support.

Best regards
