### ISSUE TITLE
TEP 0700 imx7 Android 7.1.1 WebView not working

### ISSUE THREAD

**Issue by VaporMontey** [technexion-android/cookers#34]
Hello,

I'm trying to launch an application with a WebView on Android 7.1.1 downloaded from your [repository](https://download.technexion.com/demo_software/TEP/IMX7/tep0700-imx7d/archived/tep1-imx7d_android-7.1.1_installer_lcd-800x480_20180717.zip) on the TEP (model TEP0700IMX7DR10E04L130) but every times I get this Log (even using other applications with WebView inside):

[FATAL:gpu_info_collector_android.cc(193)] failed to create a pbuffer surface for fetching driver strings. EGL_SUCCESS (3000)

Best regards

**Comment by wigcheng** [comment]
Android 7 already EOL by Google, how about use Android 8 or above? And according your previous questions on github issue ticket, you're focus on Android 9 now, this also version has WebView issue or not? Thanks

**Comment by VaporMontey** [comment]
Hello,

I was trying to use Android 7.1.1 as a temporary solution because the RS232 port on the TEP with Android 9 is giving me issues. On Android 9 I don't have issue using WebView.

Best regards

**Comment by wigcheng** [comment]
I suggest close this ticket and focus on UART issue fix together, spend effort to fix an EOL revision doesn't make sense, Android 9 should be support until 2022, hope you understand.

Thanks a lot

**Comment by VaporMontey** [comment]
Ok, I'll link issue #33 and continue there.

Best regards
