### ISSUE TITLE
SELinux Policy Android 9

### ISSUE THREAD

**Issue by VaporMontey** [technexion-android/cookers#37]
Hello,

There is a way to set SELinux policy to 0 (permissive) as default when making the image?
In the current state it defaults to 1 (enforcing) and I need to set it to 0 (permissive) manually every time the device reboots using adb.
```
su
setenforce 0
```

Best regards

**Comment by wigcheng** [comment]
Sure, please add an append string 'androidboot.selinux=permissive' to device/fsl/imx7d/tep1_imx7/BoardConfig.mk BOARD_KERNEL_CMDLINE argument as follows:

BOARD_KERNEL_CMDLINE := console=ttymxc2,115200 init=/init video=mxcfb0:dev=lcd,800x480@60,if=RGB24,bpp=24 video=mxcfb1:off androidboot.console=ttymxc2 consoleblank=0 androidboot.hardware=freescale cma=320M loop.max_part=7 **androidboot.selinux=permissive** quiet

Thanks

**Comment by VaporMontey** [comment]
Hello,

Your suggestion worked perfectly, thanks a lot.

Best regards
