### ISSUE TITLE
imx7d pico pi, Invalid vbmeta image

### ISSUE THREAD

**Issue by Natr1x** [technexion-android/cookers#38]
## Clean checkout and cook does not seem to produce working images

I have been having a lot of trouble building a working image for pico pi imx7d. 
The `cook -j12` command does not seem to produce either valid vbmeta images or perhaps not signing partitions correctly.

## What I have tried:

On an `Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)` running in virtual box.

### 1. I checked the repository with repo:

``` bash
$ python3 repo init -u https://github.com/technexion-android/manifest -b tn-p9.0.0_2.2.0-ga
$ python3 repo sync -j12
```

### 2. I build the docker environment:

```bash
$ cd cookers
$ docker build -t build_droid9 .
$ sudo docker run --privileged=true --name mx9_build  -v /srv/technexion-android:/home/mnt -t -i build_droid9 bash
```

### 3. I set up the environment in docker and built with the cook command:

```bash
$ source cookers/env.bash.imx7d.pico-imx7.pi.lcd-5-inch
$ merge_restricted_extras
$ cook -j12
```

### 4. In the docker container I generated a virtual image for flashing:

```bash
$  gen_virtual_images
```

### 5. I copied and flashed the image from a laptop running windows

I copied the image with scp and I flashed using your provided mfgTool, SPL, and u-boot image. 
Taken from [imx-mfg-uuu-tool_20220207.zip](https://download.technexion.com/development_resources/development_tools/installer/imx-mfg-uuu-tool_20220207.zip) `07-Feb-2022 07:41             9641302`

```ps1
> .\imx-mfg-uuu-tool\uuu\windows64\uuu.exe -b emmc_imx7_img .\imx-mfg-uuu-tool\imx7\pico-imx7\imx7-SPL ..\test.img
```

### 6. I then powered on the device after putting the board back into regular boot mode (from serial boot)

Here are the putty logs from the uart debug port:

```
   
U-Boot SPL 2018.03-g4abbd9a (Apr 06 2022 - 15:04:59 +0000)
Trying to boot from MMC1


U-Boot 2018.03-g4abbd9a (Apr 06 2022 - 15:04:59 +0000)

CPU:   Freescale i.MX7D rev1.3 1000 MHz (running at 792 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 41C
Reset cause: POR
Board: PICO-IMX7D
Compatible baseboard: dwarf, hobbit, nymph, pi
I2C:   ready
DRAM:  512 MiB
PMIC: PFUZE3000 DEV_ID=0x30 REV_ID=0x11
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)
No panel detected: default to MCIMX28LCD
Display: MCIMX28LCD (800x480)
Video: 800x480x24
In:    serial
Out:   serial
Err:   serial
flash target is MMC:0
Net:   FEC0
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  1  0 
RNG instantiation done (3600)
Error: blob decap job failed 0x2000071a
Error during blob decap operation: 0x2000071a
In boota get fastboot lock status error. Set lock status
RNG already instantiated 0x40000003
avb_vbmeta_image.c:59: ERROR: Magic is incorrect.
avb_slot_verify.c:703: ERROR: vbmeta: Error verifying vbmeta image: invalid vbmeta header
 verify FAIL, state: LOCK
```

**Comment by wigcheng** [comment]
I think the root cause is in  gen_virtual_images command.
Please use this command on host PC side, don't in the container because container cannot access hardware relate nodes.

If still doesn't works, please provide gen_virtual_images output log to me, thanks.

**Comment by Natr1x** [comment]
When you say host pc side, you mean not in the docker container right? Not outside of the virtual box I am running it on.

**Comment by wigcheng** [comment]
Right, only compile source code in the docker container, and make image outside the container, still doesn’t works?

**Comment by Natr1x** [comment]
Unsure, I am going to try it but I am a bit sceptical about this gen_virtual_images function.
Like why does it make the partitions twice, once after it has detached the loop device.

```bash
~#@❯  gen_virtual_images
'/srv/sensidose/technexion-android/device/fsl/common/tools/gpt_partition_move' -> '/srv/sensidose/technexion-android/out/target/product/pico_imx7/gpt_partition_move'
Find /srv/sensidose/technexion-android/out/target/product/pico_imx7/fsl-sdcard-partition-virtual-image.sh
3400+0 records in
3400+0 records out
3565158400 bytes (3.6 GB, 3.3 GiB) copied, 7.05305 s, 505 MB/s
./fsl-sdcard-partition-virtual-image.sh: line 116: [: too many arguments
make gpt partition for android: partition-table-3GB.img
dd: unrecognized operand '/dev/loop4'
Try 'dd --help' for more information.
failed to stat() /dev/loop8
/dev/loop4
/dev/loop9
/dev/loop7
losetup: /dev/loop8
/dev/loop4
/dev/loop9
/dev/loop7: failed to use device: No such device
./fsl-sdcard-partition-virtual-image.sh: line 116: [: too many arguments
make gpt partition for android: partition-table-3GB.img
dd: unrecognized operand '/dev/loop4'
Try 'dd --help' for more information.
This is not GUID partition table
Bad Guid partition table
dd: unrecognized operand '/dev/loop4'
Try 'dd --help' for more information.
dd: unrecognized operand '/dev/loop4'
Try 'dd --help' for more information.
failed to stat() /dev/loop8
/dev/loop4
/dev/loop9
/dev/loop7
losetup: /dev/loop8
/dev/loop4
/dev/loop9
/dev/loop7: failed to use device: No such device
```

Edit:
I did try fixing that function previously but that didn't work either. However if you want I could try that again but running outside of the docker container.

**Comment by Natr1x** [comment]
So I made some changes to the gen_virtual_images function and now it works.

I essentially added some syncs, made sure to run `loop_dev=$(losetup | grep "test.img" | awk  '{print $1}')` after each kpartx -av in case it gets assigned to a different loop device, and then I probably went a bit overboard with kpartx -d for both the loop device and img to make absolutely certain that the device is detached before attaching it again.

If you want I can make it into a merge request?

**Comment by wigcheng** [comment]
That strange, I remember I tested before.
Anyway, thanks for your test, you can make a PR to this repo of course.

**Comment by Natr1x** [comment]
I created a pull request. Thank you very much for the help.
